name = "csv-processor"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_OWNER = ""  # Set via GitHub Actions
GITHUB_REPO = ""   # Set via GitHub Actions 

[observability.logs]
enabled = true
