name: Process CSV API

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to send results to'
        required: true
      file_content:
        description: 'Base64 encoded CSV content'
        required: true
  repository_dispatch:
    types: [process-csv]

permissions:
  id-token: write
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Process Request
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            const body = github.event.client_payload || {
              email: core.getInput('email'),
              file_content: core.getInput('file_content')
            };
            
            if (!body.email || !body.file_content) {
              return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Missing required fields' })
              };
            }

            // Set outputs to be used in later steps.
            core.setOutput('email', body.email);
            core.setOutput('file_content', body.file_content);

            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Processing started' })
            };

      - name: Set up Python
        if: steps.process.outputs.statusCode == 200
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Save and Process CSV
        if: steps.process.outputs.statusCode == 200
        env:
          FILE_CONTENT: ${{ steps.process.outputs.file_content }}
        run: |
          echo "$FILE_CONTENT" | base64 -d > input.csv
          python process_csv.py input.csv
        
      - name: Send email
        if: steps.process.outputs.statusCode == 200
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Your CSV Processing Results
          to: ${{ steps.process.outputs.email }}
          from: CSV Processor
          body: Please find your processed CSV results attached.
          attachments: ./output.csv
