name: Process CSV API

on:
  workflow_dispatch:
  web:
    types: [http]

permissions:
  id-token: write
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Process Request
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            const body = await request.json();
            if (!body.email || !body.file_content) {
              return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Missing required fields' })
              };
            }
            
            // Store the data for processing
            process.env.EMAIL = body.email;
            process.env.FILE_CONTENT = body.file_content;
            
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Processing started' })
            };

      - name: Set up Python
        if: steps.process.outputs.statusCode == 200
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Save and Process CSV
        if: steps.process.outputs.statusCode == 200
        run: |
          echo "$FILE_CONTENT" | base64 -d > input.csv
          python process_csv.py input.csv
        
      - name: Send email
        if: steps.process.outputs.statusCode == 200
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Your CSV Processing Results
          to: ${{ env.EMAIL }}
          from: CSV Processor
          body: Please find your processed CSV results attached.
          attachments: ./output.csv
