name: Process CSV API

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to send results to'
        required: true
      file_content:
        description: 'Base64 encoded CSV content'
        required: true
  repository_dispatch:
    types: [process-csv]

permissions:
  id-token: write
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Process Request
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Event name:', context.eventName);
            let body;
            if (context.eventName === 'repository_dispatch') {
              body = context.payload.client_payload;
            } else if (context.eventName === 'workflow_dispatch') {
              body = {
                email: context.payload.inputs.email,
                file_content: context.payload.inputs.file_content
              };
              console.log('Manual trigger inputs - email:', body.email);
              console.log('Manual trigger has file content:', !!body.file_content);
            } else {
              console.warn('Unknown event type, no inputs provided');
              body = {};
            }
            
            if (!body.email || !body.file_content) {
              core.setOutput('statusCode', '400');
              core.setFailed('Missing required fields');
              return;
            }

            // Set outputs to be used in later steps.
            core.setOutput('statusCode', '200');
            core.setOutput('email', body.email);
            core.setOutput('file_content', body.file_content);

      - name: Build Docker image
        if: steps.process.outputs.statusCode == '200'
        run: docker build -t food-impact .
          
      - name: Save and Process CSV
        if: steps.process.outputs.statusCode == '200'
        env:
          FILE_CONTENT: ${{ steps.process.outputs.file_content }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "$FILE_CONTENT" | base64 -d > input.csv
          docker run -v $(pwd):/app/host -e OPENAI_API_KEY=$OPENAI_API_KEY food-impact

      - name: Upload input CSV
        if: steps.process.outputs.statusCode == '200'
        uses: actions/upload-artifact@v4
        with:
          name: input-csv
          path: input.csv
          retention-days: 5

      - name: Upload output CSV
        if: steps.process.outputs.statusCode == '200'
        uses: actions/upload-artifact@v4
        with:
          name: output-zip
          path: output.zip
          retention-days: 60
        
      - name: Send email
        if: steps.process.outputs.statusCode == 200
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Your food impact results
          to: ${{ steps.process.outputs.email }}
          from: Food Impact Processor
          body: Please find your processed CSV results attached.
          attachments: ./output.zip
